Traceback (most recent call last):
  File "D:\programowanie\python\projekt zespołowy\oko_neptuna\architectures\ml\RandomForest\train.py", line 68, in train
    model = build_model_and_log(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programowanie\python\projekt zespołowy\oko_neptuna\architectures\ml\RandomForest\train.py", line 28, in build_model_and_log
    save_onnx(model, "RandomForest.onnx")
  File "D:\programowanie\python\projekt zespołowy\oko_neptuna\storage\save.py", line 7, in save_onnx
    onnx.save(model, output_file)
  File "C:\Users\games\anaconda3\envs\oko_neptuna\Lib\site-packages\onnx\__init__.py", line 324, in save_model
    proto = write_external_data_tensors(proto, basepath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\games\anaconda3\envs\oko_neptuna\Lib\site-packages\onnx\external_data_helper.py", line 313, in write_external_data_tensors
    for tensor in _get_all_tensors(model):
  File "C:\Users\games\anaconda3\envs\oko_neptuna\Lib\site-packages\onnx\external_data_helper.py", line 240, in _get_initializer_tensors
    yield from _get_initializer_tensors_from_graph(onnx_model_proto.graph)
                                                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RandomForestClassifier' object has no attribute 'graph'